theme = "bluloco-dark"

[editor]
mouse                  = true
cursorline             = true
true-color             = true
scrolloff              = 8
scroll-lines           = 1
color-modes            = true
auto-save              = false
bufferline             = "multiple"
rulers                 = [120]
auto-pairs             = true
shell                  = ["nu", "-c"]
completion-trigger-len = 1
idle-timeout           = 80
line-number            = "relative"

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 1

[editor.lsp]
display-messages    = true
display-inlay-hints = true

[editor.search]
smart-case = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.soft-wrap]
enable             = true
max-wrap           = 25    # increase value to reduce forced mid-word wrapping
max-indent-retain  = 0     # 40
wrap-indicator     = "↪"   # set wrap-indicator to "" to hide it
wrap-at-text-width = false

[editor.whitespace.render]
space   = "none"
tab     = "all"
newline = "none"

[editor.whitespace.characters]
# space = "·"
nbsp    = "⍽"
tab     = "▏"
newline = "⏎"
# tabpad = "·"

[editor.indent-guides]
render    = true
character = "╎"  # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"
# skip-levels = 1

[editor.statusline]
# left = [
#   "mode",
#   "spacer",
#   "separator",
#   "spacer",
#   "spinner",
#   "position-percentage",
#   "spacer",
#   "total-line-numbers",
# ]
# center = ["file-name", "version-control", "spacer", "diagnostics"]
# right = ["selections", "position", "file-type", "spacer"]
left = [
  "mode",
  "spinner",
  "file-name",
  "file-type",
  "total-line-numbers",
  "file-encoding"
]
center = []
right = [
  "selections",
  "primary-selection-length",
  "position",
  "position-percentage",
  "spacer",
  "diagnostics",
  "workspace-diagnostics",
  "version-control"
]
separator = "│"
mode.insert = "I"
mode.normal = "N"
mode.select = "S"

[keys.normal]
"A-up"    = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-down"  = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-right" = "indent"
"A-left"  = "unindent"

"A-S-up"   = ["extend_to_line_bounds", "yank", "paste_before"]
"A-S-down" = ["extend_to_line_bounds", "yank", "paste_after"]

"C-right"   = "move_next_word_end"
"C-left"    = "move_prev_word_end"
"C-S-right" = "move_next_word_start"
"C-S-left"  = "move_prev_word_start"
"C-S-up"    = "copy_selection_on_prev_line"
"C-S-down"  = "copy_selection_on_next_line"

"C-a" = ["select_all", "select_mode"]
"ret" = "open_below"

"A-backspace" = ["insert_mode", "delete_word_backward", "normal_mode"]
"A-del"       = ["insert_mode", "delete_word_forward", "normal_mode"]
"C-s"         = ":w"

y = [
  "yank_main_selection_to_clipboard",
  "normal_mode",
  "flip_selections",
  "collapse_selection"
]
Y = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "collapse_selection"
]

# Quick iteration on config changes
r = ":config-reload"
R = "goto_line_start"

# Muscle memory
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
G   = "goto_file_end"
V   = ["select_mode", "extend_to_line_bounds"]
D   = ["goto_line_start", "extend_to_line_end", "delete_selection"]

S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable

x = ["extend_line_below", "select_mode"]
X = ["extend_line_up", "extend_to_line_bounds", "select_mode"]
"S-up" = ["extend_line_below", "select_mode"]
"S-down" = ["extend_line_up", "extend_to_line_bounds", "select_mode"]

# Clipboards over registers ye ye
p = "paste_clipboard_after"
P = "paste_clipboard_before"

# If you want to keep the selection-while-moving behaviour of Helix, this two lines will help a lot,
# especially if you find having text remain selected while you have switched to insert or append mode
#
# There is no real difference if you have overriden the commands bound to 'w', 'e' and 'b' like above
# But if you really want to get familiar with the Helix way of selecting-while-moving, comment the
# bindings for 'w', 'e', and 'b' out and leave the bindings for 'i' and 'a' active below. A world of difference!
i = ["collapse_selection", "insert_mode"]
a = ["collapse_selection", "append_mode"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc   = ["collapse_selection", "keep_primary_selection"]
space = { "c" = "toggle_comments", "|" = "global_search" }

[keys.insert]
"A-up"    = ["normal_mode", "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "insert_mode"]
"A-down"  = ["normal_mode", "extend_to_line_bounds", "delete_selection", "paste_after", "insert_mode"]
"A-right" = "indent"
"A-left"  = "unindent"

"A-S-up"   = ["normal_mode", "extend_to_line_bounds", "yank", "paste_before", "insert_mode"]
"A-S-down" = ["normal_mode", "extend_to_line_bounds", "yank", "paste_after", "insert_mode"]

"C-right"   = "move_next_word_end"
"C-left"    = "move_prev_word_end"
"C-S-right" = "move_next_word_start"
"C-S-left"  = "move_prev_word_start"
"C-S-up"    = "copy_selection_on_prev_line"
"C-S-down"  = "copy_selection_on_next_line"

"tab"   = "insert_tab"
"S-tab" = "unindent"

esc = ["collapse_selection", "normal_mode"]

"C-space"  = "completion"
"C-a"      = ["select_all", "select_mode"]
"S-home"   = "goto_file_start"
"S-end"    = "goto_file_end"
"pageup"   = "page_cursor_half_up"
"pagedown" = "page_cursor_half_down"
"home"     = "goto_line_start"
"end"      = "goto_line_end_newline"

"C-s" = ":w"

" " = ["collapse_selection", ":insert-output printf ' '", "move_char_right"]

[keys.select]
# Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0   = "goto_line_start"
9   = "goto_line_end"
"G" = "goto_last_line"
# "^" = "goto_first_nonwhitespace"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]

# Visual-mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"

# Some extra binds to allow us to insert/append in select mode because it's nice with multiple cursors
tab = ["insert_mode", "collapse_selection"] # tab is read by most terminal editors as "C-i"
C-a = "select_all"

x = ["extend_line_below", "extend_to_line_bounds"]
X = ["extend_line_up", "extend_to_line_bounds"]
# Make selecting lines in visual mode behave sensibly
up   = ["extend_line_up", "extend_to_line_bounds"]
down = ["extend_line_down", "extend_to_line_bounds"]

# Clipboards over registers ye ye
d = ["yank_main_selection_to_clipboard", "delete_selection"]

# x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = [
  "yank_main_selection_to_clipboard",
  "normal_mode",
  "flip_selections",
  "collapse_selection"
]
Y = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "goto_line_start",
  "collapse_selection",
  "normal_mode"
]
p = ":clipboard-paste-replace" # No life without this
P = ":clipboard-paste-after"

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
ret = ["collapse_selection", "insert_mode"]
