watch_stylesheet: true
watch_config: true
debug: false
komorebi:
    start_command: "komorebic start --whkd"
    stop_command: "komorebic stop"
    reload_command: "komorebic stop && komorebic start --whkd"
bars:
    status-bar:
        enabled: true
        screens: ["*"]
        class_name: "yasb-bar"
        alignment:
            position: "top"
            center: false
        blur_effect:
            enabled: false
            acrylic: true
            dark_mode: false
            round_corners: false
            border_color: None
        window_flags:
            always_on_top: false
            windows_app_bar: true
        dimensions:
            width: "100%"
            height: 28
        padding:
            top: 3
            left: 3
            bottom: 0
            right: 3
        widgets:
            left: ["weather", "komorebi_workspaces", "clock", "media"]
            center: ["active_window"]
            right: ["taskbar", "language", "volume", "cpu", "memory", "bluetooth", "wifi", "home"]
widgets:
    cpu:
        type: "yasb.cpu.CpuWidget"
        options:
            label: "<span>\uf4bc</span> {info[percent][total]}%"
            label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
            update_interval: 2000
            histogram_icons:
                - '\u2581' # 0%
                - '\u2581' # 10%
                - '\u2582' # 20%
                - '\u2583' # 30%
                - '\u2584' # 40%
                - '\u2585' # 50%
                - '\u2586' # 60%
                - '\u2587' # 70%
                - '\u2588' # 80%+
            histogram_num_columns: 8
            callbacks:
                on_right: "exec cmd /c Taskmgr"
            container_padding:
                top: 0
                left: 8
                bottom: 0
                right: 0
    memory:
        type: "yasb.memory.MemoryWidget"
        options:
            label: "<span>\uefc5</span> {virtual_mem_percent}%"
            label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
            update_interval: 5000
            callbacks:
                on_left: "toggle_label"
                on_middle: "do_nothing"
                on_right: "do_nothing"
            container_padding:
                top: 0
                left: 6
                bottom: 0
                right: 8
    # media:
    #     type: "yasb.media.MediaWidget"
    #     options:
    #         label: "<span>\uf001</span> {artist} - {title}"
    #         hide_empty: true
    #         max_field_size:
    #             label: 20
    #         show_thumbnail: false
    #         controls_hide: true
    #         thumbnail_alpha: 50
    #         thumbnail_padding: 70
    #         thumbnail_corner_radius: 5
    #         icons:
    #             prev_track: "\ue892"
    #             next_track: "\ue893"
    #             play: "\ue768"
    #             pause: "\ue769"
    #         callbacks:
    #             on_left: "do_nothing"
    media:
        type: "yasb.media.MediaWidget"
        options:
            label: "{title} - {artist}"
            label_alt: "{title}"
            max_field_size:
                label: 17
                label_alt: 24
            show_thumbnail: true
            controls_only: false
            controls_left: true
            hide_empty: true
            thumbnail_alpha: 255
            thumbnail_padding: 0
            thumbnail_edge_fade: true
            icons:
                prev_track: "\uf048"
                next_track: "\uf051"
                play: "\uf04b"
                pause: "\uf04c"
            scrolling_label:
                enabled: true
                update_interval_ms: 30
                style: "left" # can be "left", "right", "bounce", "bounce-ease"
                separator: " | "
                label_padding: 1
                # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
                ease_slope: 20
                ease_pos: 0.8
                ease_min: 0.5
            media_menu:
                blur: true
                round_corners: true
                round_corners_type: "normal"
                border_color: "system"
                alignment: "right"
                direction: "down"
                offset_top: 6
                offset_left: 60
                thumbnail_corner_radius: 8
                thumbnail_size: 120
                max_title_size: 27
                max_artist_size: 60
                show_source: true
            media_menu_icons:
                prev_track: "\uf048"
                next_track: "\uf051"
                play: "\uf04b"
                pause: "\uf04c"
            container_padding:
                top: 0
                left: 0
                bottom: 0
                right: 0
            label_shadow:
                enabled: true
                color: "black"
                radius: 3
                offset: [1, 1]
            callbacks:
                on_left: "toggle_play_pause"
                on_middle: "toggle_label"
                on_right: "toggle_media_menu"
    clock:
        type: "yasb.clock.ClockWidget"
        options:
            label: "<span>\uf017</span> {%Y/%m/%d, %H:%M}"
            timezones: [] #Looking up time zone info from registry
            calendar:
                alignment: "center"
            callbacks:
                on_left: "toggle_calendar"
                on_right: "do_nothing"
    taskbar:
        type: "yasb.taskbar.TaskbarWidget"
        options:
            icon_size: 16
            animation: true
            ignore_apps:
                processes: []
                titles: []
                classes: []
            container_padding:
                top: 0
                left: 8
                bottom: 0
                right: 8
    komorebi_workspaces:
        type: "komorebi.workspaces.WorkspaceWidget"
        options:
            label_offline: "\u26a1 Offline"
            label_workspace_btn: "\udb81\udc3d"
            label_workspace_active_btn: "\udb81\udc3e"
            label_workspace_populated_btn: "\udb81\udc3e"
            label_default_name: "{index}"
            label_zero_index: true
            hide_empty_workspaces: false
            hide_if_offline: true
            animation: true
            container_padding:
                top: 0
                left: 0
                bottom: 0
                right: 0
    weather:
        type: "yasb.weather.WeatherWidget"
        options:
            label: "<span>{icon}</span> {conditions} {temp} \u00b7 \u2193 {min_temp} \u2191 {max_temp} \u00b7 {precip}"
            api_key: "3bf4cf9a7c3f40d6b31174128242807"
            update_interval: 600
            units: "metric"
            hide_decimal: true
            location: "China Pudong"
            show_alerts: true
            weather_card:
                alignment: "center"
                offset_left: 150
            callbacks:
                on_left: "toggle_card"
            icons:
                sunnyDay: "\ue30d"
                clearNight: "\ue32b"
                cloudyDay: "\udb81\udd99"
                cloudyNight: "\ue311"
                rainyDay: "\udb81\ude7e"
                rainyNight: "\udb81\ude7e"
                snowyIcyDay: "\udb81\udd98"
                snowyIcyNight: "\udb81\udd98"
                blizzardDay: "\uebaa"
                default: "\uebaa"
    volume:
        type: "yasb.volume.VolumeWidget"
        options:
            label: "<span>{icon}</span> {level}"
            label_alt: "{volume}"
            volume_icons:
                - "\ueee8" # Icon for muted
                - "\uf026" # Icon for 0-10% volume
                - "\uf027" # Icon for 11-30% volume
                - "\uf027" # Icon for 31-60% volume
                - "\uf028" # Icon for 61-100% volume
            callbacks:
                on_right: "exec cmd.exe /c start ms-settings:sound"
                on_middle: "toggle_mute"
    power_menu:
        type: "yasb.power_menu.PowerMenuWidget"
        options:
            label: "\uf011"
            uptime: False
            blur: False
            blur_background: True
            animation_duration: 100 # Milisecond
            button_row: 4 # Number of buttons in row, min 1 max 5
            buttons:
                shutdown: ["\uf011", "Shut Down"]
                restart: ["\uead2", "Restart"]
                signout: ["\udb80\udf43", "Sign out"]
                sleep: ["\u23fe", "Sleep"]
                cancel: ["", "Cancel"]
    active_window:
        type: "yasb.active_window.ActiveWindowWidget"
        options:
            label: "{win[process][name]}"
            label_alt: ""
            label_no_window: ""
            label_icon: true
            label_icon_size: 14
            max_length: 40
            max_length_ellipsis: "..."
            monitor_exclusive: false
            callbacks:
                on_left: "do_nothing"
    language:
        type: "yasb.language.LanguageWidget"
        options:
            label: "<span>\uf11c</span> {lang[language_code]}"
            label_alt: "{lang[full_name]}"
            update_interval: 1
            callbacks:
                on_left: "do_nothing"
                on_middle: "do_nothing"
                on_right: "do_nothing"
            container_padding:
                bottom: 1
    bluetooth:
        type: "yasb.bluetooth.BluetoothWidget"
        options:
            label: "<span>{icon}</span>"
            label_alt: "{device_name}"
            icons:
                bluetooth_on: "\udb80\udcaf"
                bluetooth_off: "\udb80\udcb2"
                bluetooth_connected: "\udb80\udcb1"
            callbacks:
                on_right: "exec cmd.exe /c start ms-settings:bluetooth"
    wifi:
        type: "yasb.wifi.WifiWidget"
        options:
            label: "<span>{wifi_icon}</span>"
            label_alt: "{wifi_name}"
            update_interval: 10000
            ethernet_icon: "\uf0ac"
            ethernet_label_alt: "{ip_addr}"
            animation:
                enabled: true
                duration: 200
                type: "fadeInOut"
            menu_config:
                blur: true
                round_corners: true
                round_corners_type: "normal"
                border_color: "System"
                alignment: "right"
                direction: "down"
                offset_top: 6
                offset_left: 0
                wifi_icons_secured: ["\ue670", "\ue671", "\ue672", "\ue673"]
                wifi_icons_unsecured: ["\uec3c", "\uec3d", "\uec3e", "\uec3f"]
            callbacks:
                on_left: "toggle_menu"
                on_middle: "toggle_label"
                on_right: "exec cmd.exe /c start ms-settings:network"
            container_padding:
                top: 0
                left:
                bottom: 0
                right: 8
            wifi_icons: [
                    "\udb82\udd2e", # Icon for 0% strength
                    "\udb82\udd1f", # Icon for 1-20% strength
                    "\udb82\udd22", # Icon for 21-40% strength
                    "\udb82\udd25", # Icon for 41-80% strength
                    "\udb82\udd28", # Icon for 81-100% strength
                ]
    home:
        type: "yasb.home.HomeWidget"
        options:
            label: "<span>\uf4E2</span>"
            menu_list:
                - { title: "User Home", path: "~" }
                - { title: "Download", path: "~\\Downloads" }
                - { title: "Documents", path: "~\\Documents" }
                - { title: "Pictures", path: "~\\Pictures" }
            system_menu: true
            power_menu: true
            blur: true
            border_color: "None"
            round_corners_type: "small"
            container_padding:
                top: 0
                left: 12
                bottom: 0
                right: 12